--CREATION OF THE TABLE STATION 

CREATE TABLE STATION (
    ID INT,
    CITY VARCHAR(21),
    STATE VARCHAR(2),
    LAT_N FLOAT,       -- Northern Latitude
    LONG_W FLOAT       -- Western Longitude
);

--INSERTION IN THE TABLE STATION 
INSERT INTO STATION (ID, CITY, STATE, LAT_N, LONG_W) VALUES
(1, 'Phoenix', 'AZ', 33.45, 112.07),
(2, 'New York', 'NY', 40.71, 74.01),
(3, 'Denver', 'CO', 39.74, 104.99),
(4, 'Seattle', 'WA', 47.61, 122.33),
(5, 'Miami', 'FL', 25.76, 80.19);

--DISPLAYING THE TABLE 
SELECT * FROM STATION 

--QUERY EXECUTION 
SELECT 
ROUND(
ABS(MIN(LAT_N)-MAX(LAT_N))+ ABS(MIN(LONG_W)-MAX(LONG_W)),
4) AS MANHATTAN_DISTANCE
FROM STATION 