--CREATION OF TABLE BST
CREATE TABLE BST(
	N INT,
	P INT);

--INSERTION IN THE TABLE BST
INSERT INTO BST
VALUES(1,2),
(3,2),
(6,8),
(9,8),
(2,5),
(8,5),
(5,NULL)

--QUERY EXECUTION ON TABLE BST
SELECT N, 
	CASE
		WHEN P IS NULL THEN 'ROOT'
		WHEN N NOT IN (SELECT DISTINCT P FROM BST WHERE P IS NOT NULL) THEN 'LEAF'
		ELSE 'INNER'
	END AS NODETYPE 
	FROM BST 
	ORDER BY N;