
--CREATION OF THE TABLE OCCUPATIONS
CREATE TABLE OCCUPATIONS (
NAME VARCHAR(30),
OCCUPATION VARCHAR(40));

--INSERTION IN THE TABLE OCCUPATIONS
INSERT INTO OCCUPATIONS 
VALUES ('SAMANTHA','DOCTOR'),
('JULIA','ACTOR'),
('MARIA','ACTOR'),
('MEERA','SINGER'),
('ASHLEY','PROFESSOR'),
('KETTY','PROFESSOR'),
('CHRISTEN','PROFESSOR'),
('JANE','ACTOR'),
('JENNY','DOCTOR'),
('PRIYA','SINGER')

--CREATING THE RANK / ROW_NUMBER
SELECT NAME , OCCUPATION , 
ROW_NUMBER()OVER(PARTITION BY OCCUPATION ORDER BY NAME ) AS RN
FROM OCCUPATIONS 
ORDER BY NAME

--QUERY IMPLEMENTATION ON OCCUPATION TABLE
SELECT 
	MAX(CASE WHEN OCCUPATION= 'DOCTOR' THEN NAME END) AS DOCTOR,
	MAX(CASE WHEN OCCUPATION= 'PROFESSOR' THEN NAME END) AS PROFESSOR,
	MAX(CASE WHEN OCCUPATION= 'SINGER' THEN NAME END) AS SINGER,
	MAX(CASE WHEN OCCUPATION= 'ACTOR' THEN NAME END) AS ACTOR
FROM (SELECT NAME , OCCUPATION , 
ROW_NUMBER()OVER(PARTITION BY OCCUPATION ORDER BY NAME ) AS RN
FROM OCCUPATIONS 
) AS TEMP
GROUP BY RN;